### ISSUE TITLE
This SDK not work with Azure China Azure Data Explorer

### ISSUE THREAD

**Issue by nonokangwei** [Azure/azure-kusto-java#121]
**Describe the bug**
the client create api nowhere to specify the cloud china, it always using the global azure login endpoint. 

**To Reproduce**
Steps to reproduce the behavior: using the china adx cluster address do connection

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ohadbitt** [comment]
To work with other clouds use the environment variable : 
AadAuthorityUri
For example for public cloud - set AadAuthorityUri to https://login.microsoftonline.com/
