### ISSUE TITLE
Is there a Kusto Android SDK?

### ISSUE THREAD

**Issue by shahzaibj** [Azure/azure-kusto-java#145]
This SDK (Kusto JAVA SDK) isn't compatible with Android as it uses the Apache's Http Client and that is deprecated on Android. 

See these for more context:

- https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p
- https://developer.android.com/about/versions/marshmallow/android-6.0-changes
- https://stackoverflow.com/questions/54652322/how-to-use-apache-http-client-4-5-x-used-by-external-library-on-android

The question is, do we actually have a Kusto SDK specifically for Android? or one at least compatible with Android that doesn't use the Apache's Http Client. If not, is there a plan to support Android?

**Comment by vladikbr** [comment]
No.
