### ISSUE TITLE
Failed to create continue query via the java API

### ISSUE THREAD

**Issue by eladwer** [Azure/azure-kusto-java#146]
**Describe the bug**
I managed to create externalTable via the api, but it failed to create continue export.
Behaviour is not consistent
the error: 
Caused by: com.microsoft.azure.kusto.data.exceptions.DataWebException: Bad request: Control commands (starting with a dot '.') cannot be served from the query endpoint unless they are .show control commands.
Please provide the following information when contacting the Kusto team:
ClientRequestId='KJC.execute;be2d9787-6e7d-44db-af0d-c370c88de3b9', ActivityId='78661026-0b7b-4ba8-bf83-b694d5381c5d', Timestamp='2020-08-05T12:51:31.0018478Z'.
	... 55 more

Did not find any other api for the control plan.

**To Reproduce**
scala example:
def createContQuery(contExportName: String, origTableName: String, externalTableName: String, queryWithProjection: String): String = {
     s"""
        create-or-alter continuous-export $contExportName
        over ($origTableName)
        to table $externalTableName
        with
        (intervalBetweenRuns=1m,
         sizeLimit=104857600
        )
        <| $queryWithProjection
      """
  }

    val contExportResult: KustoOperationResult =  kustoConn.execute(database, contExportQuery)

**Expected behavior**
create continue export
**Screenshots**

**Desktop (please complete the following information):**
mac os catalina
java 8

**Additional context**

**Comment by vladikbr** [comment]
continous export commands should be executed against the data management endpoint ("https://ingest-<your cluster name>")
