### ISSUE TITLE
Add protections against SQL injection

### ISSUE THREAD

**Issue by maltalex** [Azure/azure-kusto-java#154]
The Kusto client takes raw Strings as queries, which is a very dangerous practice.

If part of the query contains a user-provided String (e.g. in a where clause), a malicious user could easily modify the query to run arbitrary code against the cluster.

For example consider something like `String query = "Users | where UserId = " + userIdParam";` If `userIdParam` turns out to be the string `123 ; Users | take 100`, we'd end up running the query `"Users | where UserId = 123; Users | take 100" which would return both the records for user 123 as well as 100 other records that might belong to other users. This can be used as a way of gaining access to forbidden information as well as performing denial of service attacks by running computationally expensive queries.

Every database driver I've ever seen (both relational and NoSQL) has protections against SQL injection in the form of either query builders or prepared statements, but I don't see anything of that sort in Kusto.

**Comment by vladikbr** [comment]
@yihezkel, please see that we expose the parametrized queries abilities in Java

**Comment by jPrest** [comment]
Having a protection against SQL injection is a potential blocker and mandatory for our adoption of ADX.
Is there an expected timeline for such a feature and any workaround until this will be available?

**Comment by maltalex** [comment]
jPrest The obvious workaround is employing very strict input validation although I completely agree that this is something that should be provided by the sdk.

**Comment by jPrest** [comment]
@maltalex 
Fully agreed, this is a feasible workaround. 
But it is very error prone and thus a constant security risk, especially if the code base is evolving and features get added.

**Comment by yihezkel** [comment]
@jPrest thanks for the ping on this. We don't have a specific timeline, but it is the 2nd highest priority feature request in this SDK, so I intend to implement it soon.

**Comment by taulant01** [comment]
@yihezkel is there any update on this topic?

**Comment by yihezkel** [comment]
Hi @taulant01,

I looked into this further, and see that parameterized queries are already supported in the Java SDK. Please see the following test I wrote:
`    @Test
    void testParameterizedQuery() throws DataServiceException, DataClientException {
        ClientRequestProperties crp = new ClientRequestProperties();
        crp.setParameter("nameParam", "myName");
        crp.setParameter("metricParam", "8");
        String query = "declare query_parameters(nameParam:string, metricParam:string); TestTable | where Name == nameParam and Metric == metricParam";
        KustoOperationResult resultObj = queryClient.execute("TestDatabase", query, crp);
        KustoResultSetTable mainTableResult = resultObj.getPrimaryResults();
        mainTableResult.next();
        int results = mainTableResult.getInt(2);
        assertEquals(8, results);
    }
`

I will try to commit a modified version of this test so others will see an example of how to use it.

**Comment by yihezkel** [comment]
I'm adding a significantly more robust interface for setting parameterized query values. Please let me know if you have any issues with it.
