### ISSUE TITLE
Why ResultSet?

### ISSUE THREAD

**Issue by maltalex** [Azure/azure-kusto-java#157]
The `KustoResultSetTable` class implements `java.sql.ResultSet`, which as its name suggests is part of Java's sql api, however it looks like Kusto chooses to implement only this one little snippet of the API without providing a JDBC driver. Without a JDBC driver, the various Java libraries for working with databases can't work with Kusto.

So why the `ResultSet`? Is a JDBC driver being worked on? Can someone please share the reasoning behind this?

**Comment by maltalex** [comment]
@yihezkel 
My contribution to the code has little to do with this question. My PR just added some convenience utilities for parsing the ResultSet. This question is about trying to understand the expected usage of the `ResultSet` the SDK returns.

**Comment by maltalex** [comment]
It's also worth mentioning #161 in this context.

**Comment by yihezkel** [comment]
The rationale for using `java.sql.ResultSet` is that it's an existing, mature interface that describes capabilities we want in our KustoOperationResults. This class, containing the results from a KQL query, **is a** ResultsSet. That also provides the concomitant convenience methods, including progressively reading the recordset which we may add in the future. This is the only portion of the Java SQL API we intend to provide.

This SDK is in no way intended to be used as a JDBC driver, nor a SQL library.
