### ISSUE TITLE
Null pointer exceptions in KustoResultSetTable

### ISSUE THREAD

**Issue by maltalex** [Azure/azure-kusto-java#158]
The primitive `getXXX` methods in `KustoResultSetTable` throw NPEs when the column value is null. This is caused by casting the nullable `Object` to the different primitive types without checking for nullability. For example:

    @Override
    public int getInt(int i)  {
        return (int) get(i);
    }

    @Override
    public long getLong(int i)  {
        Object obj = get(i);
        if(obj instanceof Integer){
            return ((Integer)obj).longValue();
        }
        return (long) obj;
    }

    @Override
    public float getFloat(int i)  {
        return (float) get(i); }

    @Override
    public double getDouble(int i)  {
        return (double) get(i);
    }

**Comment by yihezkel** [comment]
CLosing, per your contributions to the code.

**Comment by maltalex** [comment]
@yihezkel 
Again, my contribution to the code has little to do with issue. The `ResultSet` still throws NPEs when this code is executed. My PR just works around this problem by using getObject() on everything.

**Comment by yihezkel** [comment]
My mistake. We'll take a look at this and resolve when we can fit it in.

**Comment by yihezkel** [comment]
We'll add new methods that return the object version of these primitives, and if the underlying value is null, we'll return null.

**Comment by ohadbitt** [comment]
#176
