### ISSUE TITLE
KustoResultSetTable implements `ResultSet`, but does't follow it correctly

### ISSUE THREAD

**Issue by maltalex** [Azure/azure-kusto-java#161]
1. For historical reasons, the Java `ResultSet` uses 1-based column numbering (see [javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/ResultSet.html)) while `KustoResultSetTable` uses 0-based numbering 

2. According to the Javadoc, ResultSet's `getObject` method should return null for cells with a null value, but that's not what `KustoResultSetTable` does. For an empty `string` cell, we get an empty `String` instead of null. This is especially problematic for columns in which empty and null values have different meanings.

**Comment by yihezkel** [comment]
1. Other SDKs use 0-based indexing, so we'd like to keep it consistent. The intent of using SQL's ResultSet is not to be a JDBC driver, so not following the same conventions isn't an issue.
2. We'll fix this, but it'll be a breaking change, and we'll include it in an upcoming version.
Thanks for bringing these to our attention!

**Comment by ohadbitt** [comment]
For string - there is no such thing as null in kusto - only empty strings

**Comment by maltalex** [comment]
> 
> 
>     1. Other SDKs use 0-based indexing, so we'd like to keep it consistent. The intent of using SQL's ResultSet is not to be a JDBC driver, so not following the same conventions isn't an issue.

Then what's the point of implementing `ResultSet` at all? Tools and libraries that work with `ResultSet` expect a 1-based indexing, just like they expect nullability.

I humbly suggest simply changing `KustoResultSetTable` so it doesn't implement `ResultSet` at all. Instead, expose a more suitable API without trying to fit into the `ResultSet` limitations. `ResultSet` is simply not the right tool for the job.
The downside of course is that it's a breaking change, but fixing these issues would break comparability anyway so why not just migrate to a more suitable API while we're breaking things?

**Comment by ohadbitt** [comment]
Leaving it just because its not 0-based ?

**Comment by ohadbitt** [comment]
Nulls will be taken care of here : 
https://github.com/Azure/azure-kusto-java/pull/176

**Comment by maltalex** [comment]
Leaving it because it's useless for multiple reasons, one of which is that it's 0-based.
If libraries that take `ResultSet` can't handle the Kusto ResultSet due to incompatabilities, then what's the point of implementing the interface?

**Comment by maltalex** [comment]
Note that the new methods you added in #176 are already outside the ResultSet interface because the interface forces you to return `int` and not `Integer`

**Comment by ohadbitt** [comment]
Moving away from ResultSet https://github.com/Azure/azure-kusto-java/pull/180

**Comment by ohadbitt** [comment]
will be available in version 3.0.0
