### ISSUE TITLE
ignoreFirstRecord

### ISSUE THREAD

**Issue by vcarluer** [Azure/azure-kusto-java#175]
**Is your feature request related to a problem? Please describe.**
I need to import CSV files

**Describe the solution you'd like**
ignoreFirstRecord option on IngestionProperties

**Describe alternatives you've considered**
modifying the file...

**Additional context**
blocker to use ingestFromFile with CSV

**Comment by vcarluer** [comment]
In fact I achieve to do it by calling (kotlin code):
        prop.setAdditionalProperties(mutableMapOf("ignoreFirstRecord" to "true"))

**Comment by ohadbitt** [comment]
This is the way to do it.
