### ISSUE TITLE
Querying Azure Application Insights trough Azure Data Explorer Cluster

### ISSUE THREAD

**Issue by amalathask** [Azure/azure-kusto-java#182]
**Describe the bug**
Using the Java SDK I'm trying to execute a query to get data from Application Insights from the Azure Data Explorer Cluster. The data I'm trying to get are customEvents. 

The adjusted error message I'm getting is the following: 
```
com.microsoft.azure.kusto.data.exceptions.DataServiceException: not authorized to access resource name: -, resource id: , in cluster, scoped to subscription -, resource group telemetry, ActivityId='-'
	at com.microsoft.azure.kusto.data.Utils.createExceptionFromResponse(Utils.java:162)
	at com.microsoft.azure.kusto.data.Utils.post(Utils.java:65)
	at com.microsoft.azure.kusto.data.ClientImpl.executeToJsonResult(ClientImpl.java:118)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:77)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:72)
	at Main.main(Main.java:24)
```

**To Reproduce**

Followed the Prerequisites based on the README
1. Created Azure Data Explorer Cluster
2. Created Azure Active Directory App Registration
3. Added Azure Application Insights Cluster in Azure Data Explorer Portal

**Expected behavior**
The query should work and return customEvents.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.4
 - Kusto Query SDK: com.microsoft.azure.kusto:kusto-ingest:2.8.2

**Additional context**
A service request was created under #2108040050000668 whereas the recommendation was to create a issue on GitHub. Is there an official support of the Java SDK to query Azure Application Insights data trough Azure Data Explorer.

**Comment by yogilad** [comment]
Hi @amalathask ,

Are you trying to authenticate (and connect) to Azure App Insights with KustoSDK or are you trying to authenticate to the underlying Kusto Service?
Can you share your code for setting up the client with values of al l fields (minus any credentials of course)?
Are you able to access your cluster from Kusto Explorer?

**Comment by amalathask** [comment]
Hi @yogilad,

I'm using the KustoSDK.

```
public static void main(String[] args) {
        try {
            ConnectionStringBuilder csb = ConnectionStringBuilder.createWithAadApplicationCredentials(
                    System.getenv("clusterPath"),
                    System.getenv("appId"),
                    System.getenv("appKey"),
                    System.getenv("appTenant"));
            ClientImpl client = new ClientImpl(csb);

            KustoOperationResult results = client.execute(System.getenv("dbName"), System.getenv("query"));
            KustoResultSetTable mainTableResult = results.getPrimaryResults();
            System.out.println(String.format("Kusto sent back %s rows.", mainTableResult.count()));

            // iterate values
            while (mainTableResult.next()) {
                List<Object> nextValue = mainTableResult.getCurrentRow();
            }

            // in case we want to pass client request properties
            ClientRequestProperties clientRequestProperties = new ClientRequestProperties();
            clientRequestProperties.setTimeoutInMilliSec(TimeUnit.MINUTES.toMillis(1));

            results = client.execute(System.getenv("dbName"), System.getenv("query"), clientRequestProperties);
            System.out.println(results.getPrimaryResults().getData());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

For the URL I'm using the following: **_https://ade.applicationinsights.io/subscriptions/{subscription-id}/resourceGroups/{resourceGroup}/providers/microsoft.insights/components/{cluster}_**

I'm able to access the cluster from the Azure Data Explorer (https://dataexplorer.azure.com/) when I've added the Application Insights component as a cluster.

**Comment by yogilad** [comment]
Hi,
Query is possible via a proxy mentioned in the above example provided by @amalathask.
You need to use a late client version which includes some changes to the authentication flow.

**Comment by rongshabing** [comment]
Hi @yogilad 
What do you mean by a late client version? Do you have an example for that? We are currently using the newest version of the SDK and getting the same error.

**Comment by yogilad** [comment]
Hi @rongshabing ,
Can you make sure your client passes through this line?
https://github.com/Azure/azure-kusto-java/blob/cde236165432d48786c86812a0a0739e902b4f8a/data/src/main/java/com/microsoft/azure/kusto/data/auth/CloudInfo.java#L83

Also, can you share your activity id from the exception you get?

**Comment by yihezkel** [comment]
Hi @rongshabing,

In response to your question on September 1, @yogilad was referring to a relatively recent version of this client, which includes the changes he referenced. Ideally the latest version :-)

In any case, since we haven't heard from you in 5 months, we're going to close this issue. If you still need help, please reopen with a response to our questions above.
