### ISSUE TITLE
Timer Error in the QueuedIngestClient 

### ISSUE THREAD

**Issue by Juno0c** [Azure/azure-kusto-java#184]
**Describe the bug**
When using the QueuedIngestClient to conduct multi-thread ingestions to ADX, the code always throws "java.lang.IllegalStateException: Timer already cancelled." even though the ingestion is successful.

Stacktrace:
Exception in thread "Timer-58" java.lang.IllegalStateException: Timer already cancelled.
 	at java.util.Timer.sched(Timer.java:397)
	at java.util.Timer.schedule(Timer.java:193)
 	at com.microsoft.azure.kusto.ingest.ResourceManager$1RefreshIngestionResourcesTask.run(ResourceManager.java:96)
 	at java.util.TimerThread.mainLoop(Timer.java:555)
 	at java.util.TimerThread.run(Timer.java:505)

**To Reproduce**
Use the QueuedIngestClient for large numbers of parallel ingestions with Service Bus Trigger (Azure Function App)
1. ingestClient = IngestClientFactory.createClient(ConnectionStringBuilder csb);
2. ingestClient.ingestFromStream(StreamSourceInfo streamSourceInfo, IngestionProperties ingestionProperties).

**Expected behavior**
Ingestion is successful without "Timer already cancelled" Exception

**Desktop (please complete the following information):**
 - OS: Unbuntu
 - Version 18.04

**Additional Information**
The Version of azure-kusto-java in use is 2.3.1

**Comment by ohadbitt** [comment]
Hi, sorry for the late response 
It seems like timers are closed only if the client is closed - which means that you are closing the client and continue using it - note that the client is closeable
