### ISSUE TITLE
Share HTTP client across requests

### ISSUE THREAD

**Issue by margelatu** [Azure/azure-kusto-java#186]
Hi, folks, we're using a few Azure Data Explorer clusters in a multi-region deployment of a service. The service exposes a REST API, allowing its users to query data which is found in the ADX cluster -- so we're talking about a long-lived application here.

The service uses the `kusto-data` library to execute the queries against the ADX cluster, specifically one of the flavours of `com.microsoft.azure.kusto.data.Client.execute()` see https://github.com/Azure/azure-kusto-java/blob/master/data/src/main/java/com/microsoft/azure/kusto/data/Client.java#L12 

What we noticed is that the implementation of the `Client`:
  * creates a new HTTP client object for each request, along with everything it entails such as an associated connection pool, a pool manager, etc.
  * does _not_ reuse HTTP connections or clients;
  * does _not_ close the HTTP client or the connection it uses in a request.

This can be observed here: https://github.com/Azure/azure-kusto-java/blob/cde236165432d48786c86812a0a0739e902b4f8a/data/src/main/java/com/microsoft/azure/kusto/data/Utils.java#L47

This is problematic from multiple aspects:
  * from a performance perspective, each query the service makes to ADX incurs the price of creating the new client and its associated resources, creating a new connection, SSL handshake, etc.
  * from a resource perspective, this is a waste of server resources.

What the library should probably do is create and reuse an HTTP client across multiple queries / requests. The client could be created during some sort of initialisation phase and should be closed during a "close" phase.

Any thoughts or feedback about this would be greatly appreciated.

**Comment by yihezkel** [comment]
Thanks Ionut! We agree, and called this out as well when implementing a change related to the HttpClient in April:
https://github.com/Azure/azure-kusto-java/blob/master/data/src/main/java/com/microsoft/azure/kusto/data/Utils.java#L199

We'll address this as soon as priorities permit.

**Comment by margelatu** [comment]
@yihezkel Thanks for the response. Do you have a rough idea on when this could be tackled ?

**Comment by yihezkel** [comment]
Hi @margelatu ,

Would you like to make a contribution to this? If not, we'll take care of it.

**Comment by larisaad** [comment]
Hi @yihezkel, yes, we're preparing a PR for this.

**Comment by margelatu** [comment]
@yihezkel the PR is now open thanks to @larisaad , see https://github.com/Azure/azure-kusto-java/pull/196
