### ISSUE TITLE
Kusto-ingest 2.8.2 triggers "Deprecated Azure SDK libraries" warning in IntelliJ

### ISSUE THREAD

**Issue by derSchtefan** [Azure/azure-kusto-java#188]
When importing kusto-ingest via pom.xml :
```xml
<dependency>
    <groupId>com.microsoft.azure.kusto</groupId>
    <artifactId>kusto-ingest</artifactId>
    <version>2.8.2</version>
</dependency>
```

Kusto-Ingest pulls the following deprecated libraries:
* com.microsoft.azure/azure-keyvault-core
* com.microsoft.azure/azure-storage          

The Microsoft Azure IntelliJ plugin complains about it. Can you update them to the Microsoft recommendation of 
* com.azure/azure-storage-blob
* com.azure/azure-storage-file-share
* com.azure/azure-storage-queue

**Comment by ohadbitt** [comment]
#240

**Comment by AsafMah** [comment]
Upgraded.
