### ISSUE TITLE
Ability to retrieve multiple results from a single query

### ISSUE THREAD

**Issue by crowcrow** [Azure/azure-kusto-java#221]
**Is your feature request related to a problem? Please describe.**
When we have a query returning multiple `PrimaryResult` results - e.g.: `select 1; select 2`, we can get only the first result from `KustoOperationResult.getPrimaryResults`. To get the rest we need be able to filter `KustoOperationResult.getResultTables` by `WellKnownDataSet.PrimaryResult` - since it contains additional metadata tables. Currently we can't do that because `KustoResultSetTable.getTableKind` is package-private.

**Describe the solution you'd like**
Make `KustoResultSetTable.getTableKind` public

**Additional context**
Submitted a PR - #220 

Cheers!

**Comment by yihezkel** [comment]
Thanks @crowcrow for your contribution!
