### ISSUE TITLE
Some ingestion operations take an extremely long time

### ISSUE THREAD

**Issue by preston-m-price** [Azure/azure-kusto-java#224]
**Describe the bug**
I'm running the [kafka connect kusto sink](https://github.com/azure/kafka-sink-azure-kusto) and I've noticed that some calls to ingest files take an extremely long time: upwards of 5 minutes. The average call only takes .2 seconds, but these long outliers are causing issues and there is no visibility into why these requests are taking so long.

The entry point from the sink code is the [QueuedIngestClient.ingestFromFile](https://github.com/Azure/azure-kusto-java/blob/76b05b0f6338fca2662d44fee9708c0708bcfb97/ingest/src/main/java/com/microsoft/azure/kusto/ingest/QueuedIngestClient.java#L154) method which performs 2 operations: Uploading the blob, and queueing the ingestion.

Users of this client have no visibility into how long these individual operations take, or if there is tarpitting/throttling happening. I suspect in my case that there is storage account throttling happening, however I cannot get help from Azure Storage support as I cannot provide specific request/correlation IDs.

**To Reproduce**
Run high volume data ingestions through the QueuedIngestionClient.

**Expected behavior**
- Logging messages would indicate that throttling is happening (if this can be detected from the client).
- The returned `IngestionResult` would contain actual information (rather than empty collection) about the operations performed, including request/correlation IDs. 

**Screenshots**
Max file ingestion duration in seconds show significant spikes/outliers in ingestion durations:
![image](https://user-images.githubusercontent.com/5125809/155367424-5e78a602-24f6-4601-a0c4-c69e0e204967.png)

**Desktop (please complete the following information):**
- Azure VMs (Standard_F8s_v2)

**Additional context**
We are running a slightly modified form of the sink code I referenced above which is how we're able to emit the telemetry about ingest duration.

**Comment by yogilad** [comment]
Hi @preston-m-price,
Kafka works by default with queued ingestion which batches data on the service side and ingests it in bulks.
The 5m outliers seem to indicate the slack of the ingestion is pushed to the database after the default timeout for data ingestion expires.
You can change the batching policy to use shorter ingestion batching times. See [](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/batchingpolicy)

Alternatively, if you do not ingest masses of data consider enabling Streaming Ingestion on the service and using streaming ingestion in Kafka.

**Comment by preston-m-price** [comment]
Hi @yogilad, thanks for the response.
I've got a good understanding how the [kafka sink azure kusto](https://github.com/azure/kafka-sink-azure-kusto) sink works. Where we're seeing this long duration ([here](https://github.com/Azure/kafka-sink-azure-kusto/blob/6dbd611a0fbad324cc27430ed3a61fe5e447c8b4/src/main/java/com/microsoft/azure/kusto/kafka/connect/sink/TopicPartitionWriter.java#L93)) there are 2 main operations performed by the QueuedIngestClient:
- [upload the blob](https://github.com/Azure/azure-kusto-java/blob/d6075a252e8fea0b8bb590cabf0924af2b018106/ingest/src/main/java/com/microsoft/azure/kusto/ingest/QueuedIngestClient.java#L155)
- [adding the blob to the queue](https://github.com/Azure/azure-kusto-java/blob/d6075a252e8fea0b8bb590cabf0924af2b018106/ingest/src/main/java/com/microsoft/azure/kusto/ingest/QueuedIngestClient.java#L116)
The long durations we're observing only involves these operations behind the QueuedIngestClient.ingestFromFile method. I.E. when we add a new file to the queue for ingestion. I agree there seems to be a timeout of around 5 minutes involved, but it's not clear to me which of these operation(s) are consuming all that time, or why? Is it possible there is tarpitting or throttling on the Azure Storage service impacting us? How can we diagnose, or eliminate this possibility? Is this behavior normal, or are these long durations indicating there's a problem we need to address? The kafka connect sink ships with v2.8.2 of the SDK, is it possible we'd have better performance on 3.0?

Additionally, for the volume of data we want to ingest we've been steered toward using queued ingestion by the Kusto team, and we need to do frequent schema migrations, so streaming ingestion is not a good fit for us.

**Comment by yogilad** [comment]
Hi @preston-m-price ,
The link seems to have dropped from my previous answers.
Kusto's backend is the one delaying the tail of your data until a batch is sealed on time expiration with a default of 5 minutes.
Read the below to better understand the scenario and alter the default time batching to something more suitable for your needs

https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/batchingpolicy#sealing-a-batch

**Comment by yogilad** [comment]
@preston-m-price , While Java does not have timeouts around the blob uploaded and queue storage operations as in our other SDKs, the timeouts we do commonly use are around the 10m range **in order to prevent duplications**. 

We are currently in the process of upgrading the Storage client version, which may resolve your issues, but that is speculative.
In the meantime I suggest you contact Azure Storage to analyze the cause for the queueing / uploading times.
