### ISSUE TITLE
How to get JSON/POJO from the KustoResultSetTable

### ISSUE THREAD

**Issue by saumilsdk** [Azure/azure-kusto-java#233]
I want to get JSON object or array of JSON POJO objects on the query returning multiple rows. I am not comfortable with iterating each row one by one and creating those manually.

**Comment by AsafMah** [comment]
Either way you will have to create the objects - the rows we get from the server are arrays, and someone has to merge them with the columns.

We don't have anything like this built in, but you can use `getData()` to easily do it yourself - 

```java
KustoOperationResult completeResult= queryClient.execute(<databaseName>, <your query>);
KustoResultSetTable mainTableResult = completeResult.getPrimaryResults();
List<Map<String, Object>> resultMap = mainTableResult.getData()
        .stream().map(row ->
                IntStream.range(0, row.size()).
                        mapToObj(ir -> new AbstractMap.SimpleEntry<>(mainTableResult.getColumns()[ir].getColumnName(), row.get(ir)))
                        .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue)))
                        .collect(Collectors.toList());

JSONArray jsonArray = new JSONArray(resultMap);
```

**Comment by yihezkel** [comment]
Hi @saumilsdk,

We implemented `executeToJsonResult()` to bypass the conversion to `KustoResultSetTable` in the first place. It returns the `json` as a `String`, intended for specific performance scenarios.

That said, our service returns results in this `KustoResultSetTable` format, so the `json` will still need to be parsed to obtain the POJO components of it.

I want to understand your issue better, though. What do you mean by, "I am not comfortable with iterating each row one by one and creating those manually"? What exactly is the concern with working with a `KustoResultSetTable` object? Note that we have examples of working with results.
