### ISSUE TITLE
Not able to access ADX cluster deployed in a VNet

### ISSUE THREAD

**Issue by shanavt** [Azure/azure-kusto-java#264]
**Describe the bug**
ADX cluster is deployed in a VNET. Custom code running in AKS or Azure Functions cannot create records in the ADX database using the SDK. AKS and Azure Functions are in the same VNet. There are no issues with the same code when the ADX cluster is not part of the Vnet

Error Message:  **IOError when trying to retrieve CloudInfo**

Stack Trace: 
com.microsoft.azure.kusto.ingest.StreamingIngestClient.ingestFromStream(StreamingIngestClient.java:176)
com.microsoft.azure.kusto.ingest.StreamingIngestClient.ingestFromStream(StreamingIngestClient.java:137)
com.wba.Function.run(Function.java:83)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)

**To Reproduce**
Create an ADX cluster in a VNet
Access the ADX cluster to create a record a table using Kusto SDK
Auth method- Service Principle

**Comment by ohadbitt** [comment]
Hi
This does not seem to be an issue in the sdk, please follow this and report the result

https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deploy-troubleshoot?tabs=windows

Please add client version and the full stacktrace

**Comment by shanavt** [comment]
> Hi This does not seem to be an issue in the sdk, please follow this and report the result
> 
> https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deploy-troubleshoot?tabs=windows
> 
> Please add client version and the full stacktrace

That is correct. It was a network related issue.  In our case both the client service (AKS) and the ADX Clusters were part of the same VNet, but different subnet. We had to do two things to get this working.
1. Use the private URL for the ADX cluster - (It is hidden in the ADX cluster Overview page on Azure Portal)
2. Configure outbound NSG rules for AKS and inbound NSG rules for the ADX Cluster

Thanks for checking. You can close this issue.

**Comment by shanavt** [comment]
That is correct. It was a network related issue.  In our case both the client service (AKS) and the ADX Clusters were part of the same VNet, but different subnet. We had to do two things to get this working.
1. Use the private URL for the ADX cluster - (It is hidden in the ADX cluster Overview page on Azure Portal)
2. Configure outbound NSG rules for AKS and inbound NSG rules for the ADX Cluster

Thanks for checking. You can close this issue.
