### ISSUE TITLE
Imcompatible libraries

### ISSUE THREAD

**Issue by PeterGachuru** [Azure/azure-kusto-java#276]
Kindly check on the quickstart and sample apps. They are not running, some dependency versions in pom are non-existent, some classes declared in the libraries are not public.
If possible, kindly add me as a contributer to the project..

![Capture](https://user-images.githubusercontent.com/30774477/198566310-ca85a4b3-52b3-454a-851d-bfac94964e7f.PNG)
![Capture1](https://user-images.githubusercontent.com/30774477/198566872-a8d44c3f-503e-4a4c-a951-d64528195954.PNG)

**Comment by ohadbitt** [comment]
Fixed in #240
