### ISSUE TITLE
Feature Request: Make AbstractSourceInfo "public"

### ISSUE THREAD

**Issue by The-Funk** [Azure/azure-kusto-java#294]
I'm creating a wrapper library for a microservice framework and utilizing azure-kusto-java. The ingestion operations all have similar signatures, so I'd like to write a wrapper method that looks like this:

`public <T extends AbstractSourceInfo> ingestionMethod(T sourceInfo, IngestionProperties) {}`

Unfortunately, the AbstractSourceInfo class is not public, so I'm stuck writing a wrapper for each type of source info (4 types right now)

**Describe the solution you'd like**
Make the AbstractSourceInfo class public

**Describe alternatives you've considered**
Alternatively, the kusto library could do this work for me and write their own generic method to call the appropriate ingestion operation based on what sourceInfo is an instanceof (this is my intention with the wrapper). This is not super performant however it's an ingestion operation and a singular check, so I think the performance cost is worth the simplification for the user.

**Comment by yogilad** [comment]
Use the following syntax
_public <T extends **SourceInfo**> ingestionMethod(T sourceInfo, IngestionProperties) {}_
