### ISSUE TITLE
Requests fail with Http Errorcode 400 if 'x-ms-user' contains umlauts

### ISSUE THREAD

**Issue by StefanJannCH** [Azure/azure-kusto-java#305]
If the 'user' value in ClientRequestProperties.java contains umlauts (ä,ö,ü) then the request fails with an http code 400. 
The problem seems to be that umlauts are not encoded correctly in the request header ("x-ms-user").

So the client lib should make sure that values are encoded correctly in the request(-header).

**Comment by yogilad** [comment]
version 4.0.3 ought to have handled this issue.
Which version do you use?
