### ISSUE TITLE
azure-core dependency conflicts

### ISSUE THREAD

**Issue by The-Funk** [Azure/azure-kusto-java#306]
**Describe the bug**
When using other libraries that are dependent on azure-core in a project it is possible to experience dependency conflicts with azure-kusto-java due to the older version of azure-core that it depends upon.

For instance, there is a jackson dependency conflict which causes odd behavior when serializing/deserializing unless your project explicitly declares a jackson version.

**To Reproduce**
Start a new maven project and include any azure project relying on azure-core > 1.34 and azure-kusto-java >= 4.0.0.
Attempt to serialize/deserialize something with Jackson.

**Additional context**
Since azure-kusto-java depends on azure-core itself it's possible that the kusto library could just update in tandem with the other projects and roll new releases when azure-core does. I'm using the azure libraries iot-service-client and azure-messaging-eventhubs. Since these project update in tandem with azure-core in order to keep them updated I must specify explicitly which version of azure-core my project can use, so that these libraries will be happy and the kusto library will be happy as well. azure-core 1.34 seems to be that overlap. Eventually I will be forced to stop updating the other project unless the kusto library updates it's version of azure-core as well (will submit a PR later)

**Comment by nminnick** [comment]
I have the same issue with the azure-core dependency. 

I also have a dependency in my project that uses jackson 2.15.2 (azure-kust is at 2.14.2) and it is causing an issue like described in the original ticket.

**Comment by The-Funk** [comment]
This issue appears to be resolved for the moment. The newer Jackson version and azure-core versions in azure-kusto-java play nicely with newer versions used by other Azure Java libraries.
