### ISSUE TITLE
Introduce KustoRequest Object

### ISSUE THREAD

**Issue by The-Funk** [Azure/azure-kusto-java#345]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, but I'd like to ask for permission to implement a feature after PR #335 where a customer could pass a KustoQuery object (new work) which contains the properties utilized by the various execute methods in the Client interface and ClientImpl implementation. 

In these methods each property is passed individually, the database name as a String, the ClientRequestProperties map, and the query as a String. However, in the implementation, each of the execute methods chain to a single actual implementation, wherein all 3 parameters are provided (or defaulted). I'd like to provide the option for new developers utilizing the library to use an object that encapsulates these required properties, and provides defaults where appropriate. This could help to reduce the surface of the library for new developers.

**Describe the solution you'd like**
KustoClient's additionally support a single KustoQuery object as a parameter, the creation of which would be the responsibility of the user of the library. 

**Describe alternatives you've considered**
NA

Here's an example of what I'm thinking:

![image](https://github.com/Azure/azure-kusto-java/assets/3922490/a0d61a8e-ce93-4e28-abd5-b639e18f9dde)

**Comment by ohadbitt** [comment]
Sure as long as its not exposed on the API .. 
Next PR though

**Comment by The-Funk** [comment]
Implemented by #388 

Closing
