### ISSUE TITLE
API to validate queries locally

### ISSUE THREAD

**Issue by Soggywaters** [Azure/azure-kusto-java#386]
**Is your feature request related to a problem? Please describe.**
As it currently stands, there's no a clear way to know if a given KQL query is valid other than to execute it against ADX. 

**Describe the solution you'd like**
It'd be great to have support in this SDK to validate KQL queries before they are sent off to ADX.

**Describe alternatives you've considered**
The only way to know if a given KQL query works is by prefixing the entire query with `.show queryplan <| ...` and sending it off to ADX. 

Otherwise, I've built custom regex logic to validate key sections of a query and made sure that all queries coming into my service follows a specific format.

**Comment by AsafMah** [comment]
We currently publish this .NET package for parsing `KQL`, you can see it in this repo:
https://github.com/microsoft/Kusto-Query-Language

We don't plan to port this to any other language or ecosystem.

Note that even if you could syntactically validate the KQL locally, it still could fail if you mistyped names of fields or tables.
