### ISSUE TITLE
Cache JWT token instead of calling acquireAccessToken() for every request. This causes a massive performance hit

### ISSUE THREAD

**Issue by rjdkolb** [Azure/azure-kusto-java#44]
For every call of the [KustoClient](https://github.com/Azure/azure-kusto-java/blob/master/data/src/main/java/com/microsoft/azure/kusto/data/KustoClient.java) execute(String command) and execute(String database, String command) a new AccessToken is requested and this token is valid for one day.

This adds about 500ms to every request

Please cache this JWT and only renew once expired.

**Comment by rjdkolb** [comment]
![aquire_access_token](https://user-images.githubusercontent.com/1104824/48062121-bd92f100-e1c9-11e8-9382-e8e5d30a0605.png)

**Comment by tamirkamara** [comment]
resolved #70
