### ISSUE TITLE
Add PersistentStorageFactory 

### ISSUE THREAD

**Issue by tamirkamara** [Azure/azure-kusto-java#59]
This was opened per @toshetah request as part of the review of #58.

We need to think about the necessity of such a factory since currently the "basic" AzureStorageHelper is used internally and created directly when required. The IngestClientImp constructor that allows setting the AzureStorageHelper isn't publicly visible to users and only used internally in the package.

**Comment by vladikbr** [comment]
Postponed

**Comment by yihezkel** [comment]
Closing, as cut for not having sufficient need
