### ISSUE TITLE
Library resolution failed. Cause: java.lang.RuntimeException: javax.mail:mail download failed

### ISSUE THREAD

**Issue by lotsahelp** [Azure/azure-kusto-java#95]
Constantly getting error in databricks trying to load dependencies. Tried locally installing the javax.mail 1.4.7 jar and javax.mail-api 1.6.1 jar with no luck. It appears an upstream dependency is taken on javax.mail instead of javax.mail-api.

databricks runtime version 5.4 (includes Apache Spark 2.4.3, Scala 2.11)

**Comment by lotsahelp** [comment]
The dependency on adal4j is the culprit. 1.6.0 still depends on mail 1.4.7. 1.6.1 changes the dependency to mail 1.6.1 which should be mail-api 1.6.1.

**Comment by ohadbitt** [comment]
couldn't reproduce
